stages:
  - lint
  - build
  - test


variables:
  RUST_BACKTRACE: 1
  BUILD_MODE: debug

# Define common cache, used across jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}-common-cache
  paths:
    - ~/.cache/pre-commit
    - ~/.cargo
    - nautilus_core/target
    - .venv/
    - build/annotated/
    - build/optimized/
  expire_in: 26 hours

lint-job:
  stage: lint
  image: python:${PYTHON_VERSION}
  before_script:
    - pip install pre-commit
    - pre-commit install
  script:
    - pre-commit run --all-files
  only:
    - master
    - develop
  cache:
    key: ${CI_COMMIT_REF_SLUG}-pre-commit-cache-${PYTHON_VERSION}
    paths:
      - ~/.cache/pre-commit
    expire_in: 12 hours
  parallel:
    matrix:
      - PYTHON_VERSION: [ "3.9.18", "3.10", "3.11" ]

build-job:
  stage: build
  image: ubuntu:focal  # Use ubuntu as base image
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update && apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev
      libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev
      python-openssl git clang
    - curl https://pyenv.run | bash
    - export PATH="/root/.pyenv/bin:$PATH"
    - eval "$(pyenv init -)"
    - eval "$(pyenv virtualenv-init -)"
    - pyenv install $PYTHON_VERSION
    - pyenv global $PYTHON_VERSION
    - python --version  # To check the Python version
  script:
    - echo "Setting up Rust tool-chain..."
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - source $HOME/.cargo/env
    - rustup default stable
    - rustup component add rustfmt clippy

    - echo "Installing build dependencies for Python..."
    - pip install --upgrade pip setuptools wheel pre-commit poetry==1.5.1

    - echo " Installing Python dependencies using Poetry..."
    - poetry install --only main --all-extras

    - echo "Installing and running Redis..."
    - apt-get install redis-server -y
    - redis-server --daemonize yes

#    - echo "Running cargo tests..."
#    # Dynamically set LD_LIBRARY_PATH for the installed Python version
#    - PYTHON_LIB_PATH=$(pyenv prefix)/lib
#    - export LD_LIBRARY_PATH=$PYTHON_LIB_PATH:$LD_LIBRARY_PATH
#    - make cargo-test

#    - echo "Running Python tests..."
#    # Conditional execution based on branch
#    - |
#      if [ "$CI_COMMIT_REF_NAME" = "cloudbet" ]; then
#        echo "Running Python tests for cloudbet branch..."
#        make pytest-cloudbet
#        exit 0  # Exit the script after running make pytest-cloudbet
#      else
#        echo "Running standard Python tests..."
#        make pytest
#        make test-examples
#      fi

  only:
    - master
    - develop
    - cloudbet

  parallel:
    matrix:
      - PYTHON_VERSION: ["3.9.18", "3.10"]

# Test job
test-job:
  stage: test
#  image: ubuntu:focal
  dependencies:
    - build-job
  script:
    - echo "Running cargo tests..."
    # Dynamically set LD_LIBRARY_PATH for the installed Python version
    - PYTHON_LIB_PATH=$(pyenv prefix)/lib
    - export LD_LIBRARY_PATH=$PYTHON_LIB_PATH:$LD_LIBRARY_PATH
    - make cargo-test`
    - echo "Running python tests in the project..."
    # Conditional execution based on branch
    - |
      if [ "$CI_COMMIT_REF_NAME" = "cloudbet" ]; then
        echo "Running Python tests for cloudbet branch..."
        make pytest-cloudbet
        exit 0  # Exit the script after running make pytest-cloudbet
      else
        echo "Running standard Python tests..."
        make pytest
        make test-examples
      fi
  artifacts:
    when: always
    reports:
      junit: report.xml
  only:
    - master
    - develop
    - cloudbet
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.9.18", "3.10"]
